//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IotInvoice
    {
        public decimal INTERFACE_LINE_ID { get; set; }
        public string BATCH_SOURCE_NAME { get; set; }
        public Nullable<decimal> SET_OF_BOOKS_ID { get; set; }
        public string LINE_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CUST_TRX_TYPE_NAME { get; set; }
        public Nullable<decimal> CUST_TRX_TYPE_ID { get; set; }
        public string TERM_NAME { get; set; }
        public Nullable<decimal> TERM_ID { get; set; }
        public Nullable<decimal> ORIG_SYSTEM_BILL_CUSTOMER_ID { get; set; }
        public string METER_ID { get; set; }
        public string ORIG_SYSTEM_BILL_ADDRESS_REF { get; set; }
        public Nullable<decimal> ORIG_SYSTEM_BILL_ADDRESS_ID { get; set; }
        public string CONVERSION_TYPE { get; set; }
        public Nullable<System.DateTime> CONVERSION_DATE { get; set; }
        public Nullable<decimal> CONVERSION_RATE { get; set; }
        public Nullable<decimal> CUSTOMER_TRX_ID { get; set; }
        public Nullable<System.DateTime> TRX_DATE { get; set; }
        public Nullable<System.DateTime> GL_DATE { get; set; }
        public Nullable<System.DateTime> BILLING_FROM { get; set; }
        public Nullable<System.DateTime> BILLING_TO { get; set; }
        public Nullable<decimal> LAST_METER_READING { get; set; }
        public Nullable<decimal> CURRENT_METER_READING { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public string TRX_NUMBER { get; set; }
        public string LINE_NUMBER { get; set; }
        public Nullable<decimal> UNITS_CONSUMED { get; set; }
        public Nullable<decimal> UNIT_SELLING_PRICE { get; set; }
        public Nullable<decimal> UNIT_STANDARD_PRICE { get; set; }
        public string TAX_CODE { get; set; }
        public string UOM_CODE { get; set; }
        public string LEGAL_ENTITY_ID { get; set; }
    }
}
